/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define SRAM_ADDRESS1    0x20000004U

int main(void)
{
	uint32_t value = 0;
	uint32_t volatile *p = (uint32_t*) SRAM_ADDRESS1;//якщо ми не поставимо тут volatile і спробуємо оптимізувати наш код, далі змінимо під час виконання значення адреси, то ми перекнкмося в другий цикл, через те що компілятор після першого зчитування значення припускає що вказівник не зміниться, це може і добре для ПК, але для мікроконтролерів в яких купу переривань з зовнішнього світу, це не спрацює, а зашкодить.
	while(1){
		value = *p;
		if(value){
			break;
		}
	}

	while(1);
    /* Loop forever */
	for(;;);
}
